services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "utrip_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root_pass"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_SERVER_URL: "http://localhost:9000"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    command:
      redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis_commander_ui
    environment:
      REDIS_HOSTS: "local_redis:redis:6379"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_CLUSTERS: "default"
    ports:
      - "8086:8086"
    depends_on:
      - redis
    restart: always

  app:
    build: .
    container_name: utrip_app
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/utrip_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_pass

      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

      # Redis configuration - explicitly set all values
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      TELEGRAM_SECRET: ${TELEGRAM_SECRET}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

      JAVA_OPTS: "-Xms256m -Xmx512m"

    restart: unless-stopped

volumes:
  minio_data: {}
  postgres_data: {}
  redis_data: {}