spring:
  application:
    name: utrip


  security:
    cors:
      allowed-origins: "http://localhost:3000,"
      allowed-methods: "*"
      allowed-headers: "*"

  # JPA configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres

  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres
    postgresql:
      transactional:
        lock: false

# Tomcat configuration
server:
  port: 8080


telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    webhookUrl: ${TELEGRAM_WEBHOOK_URL}
    webhookPath: /api/v1/webhook/telegram
    secret: ${TELEGRAM_SECRET}

logging:
  config: classpath:log4j2.yml

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-ttl: 90000000
  refresh-ttl: 90000000

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
