spring:
  application:
    name: utrip


  security:
    cors:
      allowed-origins: "http://localhost:3000,"
      allowed-methods: "*"
      allowed-headers: "*"

  # JPA configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/utrip_db
    username: mark
    password: root_pass
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres

  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres
    postgresql:
      transactional:
        lock: false

# Tomcat configuration
server:
  port: 8080


telegram:
  bot:
    token: "7842494007:AAGfrUvghIeZY1gDUrcFzXFEWFzH31MkBlE"
    webhookUrl: "https://d9e8c077a431.ngrok-free.app/api/v1/webhook/telegram"
    webhookPath: "/api/v1/webhook/telegram"
    secret: "secret"

logging:
  config: classpath:log4j2.yml

jwt:
  secret-key: "4b86333279995c2cf2a0595e4deead09528d2c81050021b1c76a52b95ac533f6"
  access-ttl: 900000
  refresh-ttl: 900000


minio:
  endpoint: http://localhost:9000
  accessKey: "minioadmin"
  secretKey: "minioadmin"
